### ISSUE TITLE
Can't setup sample .ovpn configuration

### ISSUE THREAD

**Issue by sb0y** [rbsgn/tunnelblick#2]
Hi.
Tunnelblick 3.7.5a (build 5011)
Trying to setup sample .ovpn config from here:
https://github.com/rbsgn/tunnelblick/blob/master/third_party/openvpn/install-win32/sample.ovpn

Got error 
![image](https://user-images.githubusercontent.com/1107273/39403654-87bb3bcc-4b89-11e8-8b45-62f575638088.png)

Please fix :(

**Comment by sb0y** [comment]
Why symbols `#&;:~|?'"~<>^[]{}$%*` are disallowed? Whey are needed for openvpn configuration!

**Comment by rbsgn** [comment]
I'm not Tunnelblick author so I can't speak why it's implemented this way. This repo is hosted on GitHub by accident and should be deleted.
